.travis.yml, README.md, __tests__/Audit.test.js, __tests__/RenderConsole.test.js, __tests__/app.test.js, __tests__/fixtures/multiple-vulnerabilities.json, __tests__/fixtures/no-vulns.json, __tests__/fixtures/one-medium-vulnerability.json, bin/is-website-vulnerable.js, index.js, package.json, src/Audit.js, src/RenderConsole.js, yarn.lock
Introduces basic support for scanning a website and showing results in a terminal output 
Initial version
Unit and integration testing added
=> feat(scan): scan a website for javascript vulnerabilities

README.md
https://github.com/lirantal/is-website-vulnerable/issues/8
Clearer documentation!
=> doc(readme): Fix small typo

src/Audit.js
Linux distributions may not correctly execute Chrome due to requiring a non-sandbox environments or other privileges.
Updated chrome flags when being executed.
Fixes https://github.com/lirantal/is-website-vulnerable/issues/12
=> fix(linux): chrome flags to support linux execution

bin/is-website-vulnerable.js, package.json, src/Audit.js
Enables running the module with debug mode enabled:
```bash
DEBUG=* is-website-vulnerable https://google.com
```
Enable easier debugging
=> feat(debug): enable debugging

bin/is-website-vulnerable.js, src/Audit.js, yarn.lock
Do not show the progress-bar if the `--json` option is provided to keep things clean.
Keeping things clean and tidy for parsing.
=> Hide the progress-bar if --json is provided

CONTRIBUTING.md
This PR updates the contributing guidelines with the right information regarding commitlint.
=> docs: remove outdated commit script, a hook is used now

package.json, yarn.lock
Fixes #26 due to lighthouse dep tree probably
=> fix(lighthouse): pin lighthouse version for known deps

npm-shrinkwrap.json, package.json, yarn.lock
Pin all deps in `package.json` to known working versions and pin all transitive dependencies as well to avoid sporadic breakage in the future.
#26
=> fix(deps): pin all deps and enforce them with shrinkwrap

src/RenderConsole.js
As a follow-up to #21 - fixing the styling in the outpu
#6
=> fix(libs): fix the libraries output style

README.md
=> fix(readme): update usage with new optional flag.

.github/workflows/main.yml
Perform the release as it's own dedicated step
https://github.com/lirantal/is-website-vulnerable/issues/37
=> chore: update CI for release step

src/Audit.js
FIx for lighthouseSettings misspelled
Change the name of the variable
[36](https://github.com/lirantal/is-website-vulnerable/issues/36)
Readable code
Run unit tests
Run basic flow
=> fix: lighthouseSettings misspelled

README.md
Updating readme with the support of the new device type flags
Documentation 
Better documentation better usage
n/a
=> fix(readme): update device type flags

__tests__/RenderJson.test.js, bin/is-website-vulnerable.js, src/RenderConsole.js, src/RenderJson.js
- Show library information in json when `--js-lib` and `--json` flag
- Change json key from `result` to `vulnerabilities` and its empty state to be `[]` instead of string
#30
=> feat(libs): print library information in json rendering

.gitignore, README.md, __tests__/Audit.test.js, bin/is-website-vulnerable.js, src/Audit.js
Added a chromePath parameter to use custom chrome path
Usage:
npx is-website-vulnerable.js https://www.github.com   (use default chrome)
npx is-website-vulnerable.js https://www.github.com --chromePath=/CustomPath/Chromium (use custom chrome)
This pull request fixes [https://github.com/lirantal/is-website-vulnerable/issues/22](Issue #22  )
=> fixes (#22): introduce chromePath parameter to use custom chrome path 

npm-shrinkwrap.json, package.json
Syncs semantic-release versions of deps.
Upgrade deps to remove peer dependency install warnings.
Fixes #54
=> fix(deps): semantic-release versioning sync

Dockerfile, README.md
This PR contains a Dockerfile for containerization of is-website-vulnerable that can be consumed under dockerhub account of @lirantal.
#52 
For one-off isolated runs of is-website-vulnerable using Docker containers. 
Tested locally by building the Docker Image.
Performing Docker runs of the image using default value for ENV SCAN_URL as well as custom values specified during docker runs.
=> containerization of is-website-vulnerable and README updated

README.md, __tests__/Audit.test.js, bin/is-website-vulnerable.js, npm-shrinkwrap.json, package.json, src/Audit.js
<p align="center"><img src="https://user-images.githubusercontent.com/22768990/71213669-c99e1d00-22bc-11ea-8bfe-de1fa318a02c.png" width="500"></p>
(image source: https://aquarium.org/sea-otter-holding-facility/)
This PR makes the CLI gracefully handle cases where a URL isn't provided to the CLI by the user, by asking for it while running (using [`inquirer`](https://github.com/SBoudrias/Inquirer.js), since I've used it in the past and know it works well).
This fixes #56.
#56
I locally tested the CLI to make sure this works.
=> Gracefully handle missing URL argument

bin/is-website-vulnerable.js, npm-shrinkwrap.json, package.json
<p align="center"><img src="https://user-images.githubusercontent.com/22768990/71382595-514b9a80-25e1-11ea-979b-7ae5c8af7e13.jpg" alt="Red Panda" width="700"></p>
(image source: https://en.wikipedia.org/wiki/File:Red_Panda_(25193861686).jpg)
This is pretty much a fixup PR for #58, fixing some of the stuff we didn't get to work on yet.
See https://github.com/lirantal/is-website-vulnerable/pull/58#discussion_r360139947 and https://github.com/lirantal/is-website-vulnerable/pull/58#issuecomment-568587251.
Locally, on my machine.
=> Refactor error handling and verify given URL is valid

bin/is-website-vulnerable.js, bin/prompt-url-input.js
Refactoring script is-website-vulnerable.js
[Feat: refactor bin/is-website-vulnerable.js](https://github.com/lirantal/is-website-vulnerable/issues/60)
I did not add new tests. All old tests were successful.
=> Refactor is-website-vulnerable.js

.dockerignore, Dockerfile, README.md
* Use node image instead of default alpine image
* Add a .dockerignore file to avoid sending everything to the docker
daemon as it's not needed
* Use node user instead of root
* Use a more complete LABEL instruction
* Install prod only packages with npm
* Don't write 1.0 in docker build as it's not true
* Move --no-cache docker build option earlier in the command as the
manual suggests
* Add --rm flag so container is deleted after the run instead of lying
around dead, never to be used again
* Add syntax highlighting in code blocks on README
* Remove whitespaces from README
This set of changes reduces the Docker image size by 30 Mb.
Fix #63 
Using specialized docker image is always better than to install node on a normal image. Using the unprivileged node user is better than using root …
=> Improve Dockerfile and README

README.md, action.yml, bin/is-website-vulnerable.js, src/Audit.js
This enables using the docker container as a Github Action.
If any vulnerabilities are detected, exit with error code 2, so the Github action can fail.
Tune that @v1 in the README for whatever the release ends up being tagged.
p.s. - Javascript isn't my primary thing, so feel free to be blunt if I'm doing anything silly.
=> GitHub Action

npm-shrinkwrap.json, package.json
Fixes #70 to include security updates
=> fix: upgrade deps

bin/is-website-vulnerable.js
This PR tries to handle the error with a code of PROTOCOL_TIMEOUT with a descriptive error message.
Fixes #73 
When there's a PROTOCOL_TIMEOUT error, we need to detect and gracefully handle with a descriptive error message.
Used the command to run against a website that is blocked by my ISP and received this descriptive error message.
=> Add descriptive message for protocol timeout

README.md
See https://github.com/lirantal/is-website-vulnerable/issues/74#issuecomment-710562459
GitHub's Markdown preview.
[![cute squittel](https://3.bp.blogspot.com/-nWDENZEI8dQ/WEN2tIZMLJI/AAAAAAAARyQ/rVF78cqSdsQ7w2bv3siPTjfkL_qa_qT7QCLcB/s1600/squirrel-cute%2B%2528132%2529.jpg)](https://3.bp.blogspot.com/-nWDENZEI8dQ/WEN2tIZMLJI/AAAAAAAARyQ/rVF78cqSdsQ7w2bv3siPTjfkL_qa_qT7QCLcB/s1600/squirrel-cute%2B%2528132%2529.jpg)
=> Document exit codes

.dockerignore, Dockerfile, start.sh
Allows extra arguments to be provided to the container when it runs, otherwise defaults to the normal behavior.
Fixes #88
=> build: support docker run arguments to customize

bin/prompt-url-input.js
Fixes #101  to detect running on CI and error as necessary
=> fix: an empty URL in CI will prompt for input instead of crashing
